/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andreza' at '4/11/17 10:29 PM' with Gradle 2.9
 *
 * @author andreza, @date 4/11/17 10:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
